name: denbot-website
services:
  frontend:
    container_name: denbot-frontend
    # Build the image from the Dockerfile in the frontend directory
    build: frontend
    develop:
    # Create a `watch` configuration to update the app to respond to any changes made
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: frontend
          target: /app
          # Exclude node modules
          ignore:
            - frontend/node_modules/
        # Rebuild the image if dependencies change by checking package-lock.json
        - action: rebuild
          path: frontend/package-lock.json
  backend:
    container_name: denbot-backend
    # Build the image from the Dockerfile in the backend directory
    build: backend
    develop:
      # Create a `watch` configuration to update the app to respond to any changes made
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: backend
          target: /app
          # Exclude the project virtual environment
          ignore:
            - backend/.venv/
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: backend/uv.lock
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./infra/certs:/etc/nginx/certs:ro
      # - ./infra/storage/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend